Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [104]:
import numpy as np

In [48]:
n = 10

In [92]:
np.arange(0,n,1)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [97]:
np.flip(np.arange(0,n),0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [103]:
np.diag(np.arange(n, 0, -2), k=0)

array([[10,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  2]])

In [163]:
diag_sum = np.diag(np.arange(n, 0, -2), k=0)
print(f'Сумма значений по диагонали: {np.trace(diag_sum)}')

Сумма значений по диагонали: 30


In [136]:
print(sum(np.diagonal(diag_sum)))

30


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [114]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [115]:
from numpy import linalg

In [116]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [117]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4.
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем. Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [118]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [119]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [159]:
def cosine(users_stats, next_user_stats):
    # длины векторов
    users_stats_Length = np.linalg.norm(users_stats)
    next_user_stats_Length = np.linalg.norm(next_user_stats)
    return np.dot(users_stats, next_user_stats) / (users_stats_Length * next_user_stats_Length)

In [164]:
mapping = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
similar_user = np.argmax(mapping) + 1
print(f'Самый похожий пользователь User ID {similar_user}')

Самый похожий пользователь User ID 8
