In [26]:
import pandas as pd
import numpy as np

In [27]:
data = pd.read_csv( 'adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
selectedColumns = data[ [ 'age', 'workclass', 'educational-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'hours-per-week', 'native-country' ] ]

In [ ]:
Переводим категориальные переменные в значения 0 и 1

In [31]:
X = pd.get_dummies( selectedColumns, columns = [ 'workclass', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country' ] )

In [32]:
X.head()

age  educational-num  hours-per-week  workclass_?  workclass_Federal-gov  \
0   25                7              40            0                      0   
1   38                9              50            0                      0   
2   28               12              40            0                      0   
3   44               10              40            0                      0   
4   18               10              30            1                      0   

   workclass_Local-gov  workclass_Never-worked  workclass_Private  \
0                    0                       0                  1   
1                    0                       0                  1   
2                    1                       0                  0   
3                    0                       0                  1   
4                    0                       0                  0   

   workclass_Self-emp-inc  workclass_Self-emp-not-inc  ...  \
0                       0                           0  ...   
1                       0                           0  ...   
2                       0                           0  ...   
3                       0                           0  ...   
4                       0                           0  ...   

   native-country_Portugal  native-country_Puerto-Rico  \
0                        0                           0   
1                        0                           0   
2                        0                           0   
3                        0                           0   
4                        0                           0   

   native-country_Scotland  native-country_South  native-country_Taiwan  \
0                        0                     0                      0   
1                        0                     0                      0   
2                        0                     0                      0   
3                        0                     0                      0   
4                        0                     0                      0   

   native-country_Thailand  native-country_Trinadad&Tobago  \
0                        0                               0   
1                        0                               0   
2                        0                               0   
3                        0                               0   
4                        0                               0   

   native-country_United-States  native-country_Vietnam  \
0                             1                       0   
1                             1                       0   
2                             1                       0   
3                             1                       0   
4                             1                       0   

   native-country_Yugoslavia  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0  

[5 rows x 89 columns]

In [33]:
# целевая переменная (столбец income) снова является категориальной
# переведем значения столбца в числа, оставив один столбец
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [34]:
le.fit( data['income'] )

LabelEncoder()

In [35]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [36]:
y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [ ]:
Обучаем модель

In [37]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [38]:
model = LogisticRegression()

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [40]:
model.fit( X_train, y_train )
predictions = model.predict( X_test )

C:\Users\CoreI7\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [41]:
predictions[:5]

array([0, 0, 0, 0, 1])

In [42]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
model.predict_proba(X_test)

array([[0.98868963, 0.01131037],
       [0.91279188, 0.08720812],
       [0.80393937, 0.19606063],
       ...,
       [0.97538971, 0.02461029],
       [0.67477049, 0.32522951],
       [0.96644129, 0.03355871]])

In [ ]:
сравниваем факт с предсказанием

In [44]:
model.score(X_test, y_test)

0.840919948133488

In [ ]:
SVM

In [45]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline


In [48]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [49]:
clf.score(X_train, y_train)

0.8341864342332329

In [50]:
clf.score(X_test, y_test)

0.8376441684296732